{% set version = '4.3.0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-fritools
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/fritools_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/fritools/fritools_{{ version }}.tar.gz
  sha256: c6a49ded375a74c940b202252eb90f5ae6c65bcb266372e7734601c00a301051

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('fritools')"           # [not win]
    - "\"%R%\" -e \"library('fritools')\""  # [win]

about:
  home: https://gitlab.com/fvafrcu/fritools
  license: BSD-2-Clause
  summary: Miscellaneous utilities, tools and helper functions for finding and searching files
    on disk, searching for and removing R objects from the workspace. Does not import
    or depend on any third party package, but on core R only (i.e. it may depend on
    packages with priority 'base').
  license_family: BSD
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/BSD_2_clause'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - thewchan

# Package: fritools
# Title: Utilities for the Forest Research Institute of the State Baden-Wuerttemberg
# Version: 4.3.0
# Authors@R: person(given = "Andreas Dominik", family = "Cullmann", role = c("aut", "cre"), email = "fvafrcu@mailbox.org")
# Description: Miscellaneous utilities, tools and helper functions for finding and searching files on disk, searching for and removing R objects from the workspace. Does not import or depend on any third party package, but on core R only (i.e. it may depend on packages with priority 'base').
# License: BSD_2_clause + file LICENSE
# URL: https://gitlab.com/fvafrcu/fritools
# Depends: R (>= 3.3.0)
# Imports: methods, stats, utils
# Suggests: callr, checkmate, covr, desc, devtools, digest, dplyr, microbenchmark, pkgload, reshape, rmarkdown, RUnit, testthat (>= 3.0.0), tinytest, whoami
# Encoding: UTF-8
# Language: en-US
# RoxygenNote: 7.2.3
# VignetteBuilder: utils
# Config/testthat/edition: 3
# NeedsCompilation: no
# Packaged: 2024-01-26 19:13:03 UTC; qwer
# Author: Andreas Dominik Cullmann [aut, cre]
# Maintainer: Andreas Dominik Cullmann <fvafrcu@mailbox.org>
# Repository: CRAN
# Date/Publication: 2024-01-26 19:50:02 UTC
